services:
  rema:
    image: rema
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rema
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
